[project]
name = "portable-power"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.1",
    "plotly>=6.2.0",
    "poethepoet>=0.36.0",
    "streamlit>=1.47.0",
]
